shadowsocks:
  image: rayruan/ss_arch:static
  ports:
    - "443:443/tcp"
    - "443:443/udp"
  volumes:
    - ./config.json:/etc/shadowsocks/config.json
  entrypoint:
    - ss-server
    - -c
    - /etc/shadowsocks/config.json
  restart: always

