version: '3'

services:
  frpc:
    image: rayruan/frp:${IMAGE_TAG}
    container_name: frpc
    ports:
      - "6000:6000/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${INSTALL_ROOT_PATH}/${INSTALL_DIR}/${CFGS_DIR}/frpc.ini:/etc/frp/frpc.ini
      - ${INSTALL_ROOT_PATH}/${INSTALL_DIR}/frpc_entrypoint.sh:/app/frpc_entrypoint.sh
    entrypoint: /app/frpc_entrypoint.sh
    restart: unless-stopped

