version: '3'

services:
  wordpress:
    image: wordpress:${WORDPRESS_TAG}
    container_name: wordpress
    restart: always
    #    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_TABLE_PREFIX=${WORDPRESS_DB_TABLE_PREFIX}
    volumes:
      - ${WORDPRESS_DATA_PATH}:/var/www/html
      - ${WP_PHP_CONFD_CONFINI}:/usr/local/etc/php/conf.d/conf.ini
    networks:
      - cms-net
      - db-net

        #volumes:
        #  wordpress:
        #    driver: local
        #    driver_opts:
        #      type: none
        #      device: ${INSTALL_ROOT_PATH}/${INSTALL_DIR}/${DATAS_ROOT_DIR}/${WORDPRESS_DIR}
        #      o: bind

networks:
  db-net:
    external:
      name: mysql_db-net
  cms-net:
    driver: bridge
    
