version: '3'

services:
  frps:
    image: ${DOCKER_TARGET}
    container_name: frps
    ports:
      - "7000:7000/tcp"
      - "6000:6000/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${INSTALL_ROOT_PATH}/${INSTALL_DIR}/${CFGS_DIR}/frps.ini:/etc/frp/frps.ini
      - ${INSTALL_ROOT_PATH}/${INSTALL_DIR}/frps_entrypoint.sh:/app/frps_entrypoint.sh
    entrypoint: /app/frps_entrypoint.sh
    restart: unless-stopped

